CREATE TABLE `crm_directory` (
`DirectoryID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`DirectoryType` INT UNSIGNED NOT NULL,
`Color` VARCHAR(45) NULL,
`Name` VARCHAR(45) NULL,
PRIMARY KEY (`DirectoryID`));

ALTER TABLE `crm_directory` 
CHANGE COLUMN `Color` `Color` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL ;

ALTER TABLE `crm_directory` 
CHANGE COLUMN `Name` `Name` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL ;
